export const APP = {
	CHANGE_USER_DATA: "CHANGE_USER_DATA"
}

export const GET_USERS = {
	GET_USERS_PENDING: "GET_USERS_PENDING",
	GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
	GET_USERS_ERROR: "GET_USERS_ERROR"
}
