export const APP = {
	CHANGE_USER_DATA: "CHANGE_USER_DATA"
}

export const GET_USER = {
	GET_USER_PENDING: "GET_USER_PENDING",
	GET_USER_SUCCESS: "GET_USER_SUCCESS",
	GET_USER_ERROR: "GET_USER_ERROR"
}
