export const DECK = {
	ADD_DECK: 'ADD_DECK',
	SHOW_ADD_DECK: 'SHOW_ADD_DECK',
	HIDE_ADD_DECK: 'HIDE_ADD_DECK'
}

export const CARD = {
	ADD_CARD: 'ADD_CARD',
	UPDATE_CARD: 'UPDATE_CARD',
	DELETE_CARD: 'DELETE_CARD',
	FILTER_CARDS: 'FILTER_CARDS',
	SET_SHOW_BACK: 'SET_SHOW_BACK'
}

export const RECEIVE_DATA = "RECEIVE_DATA"


